//
// Created by Illia Plaksa on 23.12.2021.
//

#ifndef TASKMANAGER_PROTOBUF_UTIL_TASKTOSERIALIZECOMPARERS_H_
#define TASKMANAGER_PROTOBUF_UTIL_TASKTOSERIALIZECOMPARERS_H_

#include "TaskDTO.pb.h"

bool operator==(const TaskDTO& first, const TaskDTO& second);

#endif //TASKMANAGER_PROTOBUF_UTIL_TASKTOSERIALIZECOMPARERS_H_
